### ISSUE TITLE
spatialtree is not python3.5 compatible

### ISSUE THREAD

**Issue by pratheeksh** [bmcfee/spatialtree#2]
When I ran dictionaryDemo.py under examples, I got this error -
```
Traceback (most recent call last):
  File "dictionaryDemo.py", line 43, in <module>
    T = spatialtree(X, rule='2-means', spill=0.3)
  File "/home/pks329/venv/lib/python3.5/site-packages/spatialtree-0.1-py3.5.egg/spatialtree/__init__.py", line 124, in __init__
  File "/home/pks329/venv/lib/python3.5/site-packages/spatialtree-0.1-py3.5.egg/spatialtree/__init__.py", line 170, in __split
AttributeError: 'dict' object has no attribute 'iteritems'
```

**Comment by bmcfee** [comment]
Yup, that's not surprising, given that it hasn't been updated since 2011 :grin:.  Sorry about that.

This would be easy to fix using `six` -- I don't have bandwidth to do it now, but a PR would be appreciated.
